--- !ditz.rubyforge.org,2008-03-06/project 
name: Rort
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: rort
- !ditz.rubyforge.org,2008-03-06/component 
  name: server
- !ditz.rubyforge.org,2008-03-06/component 
  name: client
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.0
  status: :released
  release_time: 2008-04-14 08:27:29.956639 Z
  log_events: 
  - - 2008-04-12 10:29:14.549433 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Be able to get a list of friends (artist with the same favorite as yourself).
  - - 2008-04-14 08:27:29.956663 Z
    - Eivind Uggedal <eu@redflavor.com>
    - released
    - We seem to have a stable base with friend functionality. First release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-14 10:55:20.683289 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Should be able to retrieve a list of recent activity for your favorites.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.3.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-14 10:57:53.567108 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Should be able to retrive a list of rencent activity for your friends.
