--- !ditz.rubyforge.org,2008-03-06/project 
name: Rort
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: rort
- !ditz.rubyforge.org,2008-03-06/component 
  name: server
- !ditz.rubyforge.org,2008-03-06/component 
  name: client
- !ditz.rubyforge.org,2008-03-06/component 
  name: doc
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.1.0
  status: :released
  release_time: 2008-04-14 08:27:29.956639 Z
  log_events: 
  - - 2008-04-12 10:29:14.549433 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Be able to get a list of friends (artist with the same favorite as yourself).
  - - 2008-04-14 08:27:29.956663 Z
    - Eivind Uggedal <eu@redflavor.com>
    - released
    - We seem to have a stable base with friend functionality. First release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.2.0
  status: :released
  release_time: 2008-04-18 11:50:32.930915 Z
  log_events: 
  - - 2008-04-14 10:55:20.683289 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Should be able to retrieve a list of recent activity for your favorites.
  - - 2008-04-18 11:50:32.930941 Z
    - Eivind Uggedal <eu@redflavor.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.3.0
  status: :released
  release_time: 2008-04-28 14:04:01.927617 Z
  log_events: 
  - - 2008-04-14 10:57:53.567108 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Should be able to display recent favorite activity on the client.
  - - 2008-04-28 14:04:01.927652 Z
    - Eivind Uggedal <eu@redflavor.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.4.0
  status: :released
  release_time: 2008-05-06 20:19:39.567008 Z
  log_events: 
  - - 2008-04-28 14:05:38.205597 Z
    - Eivind Uggedal <eu@redflavor.com>
    - created
    - Integrate Rort seamlessly into Urort
  - - 2008-05-06 20:19:39.567049 Z
    - Eivind Uggedal <eu@redflavor.com>
    - released
    - ""
